name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
  runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: docker://pandoc/core:3.5    
      uses: actions/checkout@v3

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install dependencies and build site
      run: |
        npm install
        npx hexo generate

    - name: Create .nojekyll file
      run: touch ./public/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
